---
title: "Citations"
output:
  html_document:
    theme: united
---

Cahn, Edgar. No More Throw-Away People: The Co-Production Imperative. Washington, D.C: Essential Books, 2004.

Collom, Ed, Judith Lasker, and Corinne Kyriacou. Equal Time, Equal Value: Community Currencies and Time Banking in the US. Farnham, Surrey: Ashgate, 2012. Print.

Daniels, Terry. "Interview with Terry Daniels, Initiator of HOurworld." Telephone interview. 29 Mar. 2016.

Gregory, Lee. "Spending Time Locally: The Benefit of Time Banks for Local Economies." RLCE Local Economy 24.4 (2009): 323-33.

"HOurworld: Peace, Abundance and Sharing through Equality in Exchange." HOurworld. HOurworld. Web. 1 Apr. 2016.

"Lehigh Valley Health Network - A Passion For Better Medicine." Lehigh Valley Health Network - A Passion for Better Medicine. Lehigh Valley Health Network. Web. 1 Apr. 2016.

North, Peter. “The Longevity of Alternative Economic Practices: Lessons from Alternative Currency Networks.” Interrogating Alterity Alternative Economic and Political Spaces. Farnham, Surrey: Ashgate, 2010.

Schroeder, Rolf. "The Financing of Complementary Currencies: Problems and Perspectives." International Journal of Community Currency Research 19.D (2015): 106-113.

Seyfang, Gill. "Money That Makes a Change: Community Currencies, North and South." Gender & Development 9.1 (2001): 60-69.

Seyfang, Gill. "Time Banks: Rewarding Community Self-help in the Inner City?" Community Development Journal (2004): 62-71.

Seyfang, Gill. "Give DIY Economies a Break; Local Exchange and Trading Systems are a Great Benefit to the Unemployed." New Statesman (1996).

"We Need Each Other." TimeBanks USA. TimeBanks USA. Web. 1 Apr. 2016.

Wright, Erik Olin. Envisioning Real Utopias. London: Verso, 2010. Print.


Xu, Haitong 2016